### ISSUE TITLE
when i use customize character the client closes

### ISSUE THREAD

**Issue by Friedrich1980** [Open-Games-Community/Custom-Server-13.11#3] opened 2023-04-29 17:44 UTC
when i use customize character the client closes

**Comment by Alexv45** [comment] 2023-04-29 22:06
> when i use customize character the client closes

Hello,

Can you explain and send a picture how to reproduce the error ?

**Comment by Friedrich1980** [comment] 2023-04-29 22:17
023-04-30, 00:14:06: Cannot open "C:\Users\fried\OneDrive\Desktop\Neuer Ordner\Cliente 13.11 Criando Tibia\Cliente 13.11 Criando Tibia\conf\gpublacklist.json": Das System kann die angegebene Datei nicht finden.
2023-04-30, 00:14:07: Using spritesheet cache size of 910
2023-04-30, 00:14:07: Asset loading complete
2023-04-30, 00:14:09: All sound assets loaded
2023-04-30, 00:14:15: Didn't send news query with params ( 0 2 ) (URL: QUrl("server ip") ) due to too many retries.
2023-04-30, 00:14:17: BattlEye: "Initialized (v1.246)"
2023-04-30, 00:14:17: BattlEye: "Restarting client is necessary, service isn't running properly"
2023-04-30, 00:14:17: BattlEye: "Restarting client is necessary, update required"
2023-04-30, 00:14:17: Request connection to gameserver  "tcp:xxxxxx"  (unprotected:  "tcp:xxxxxx" )  requested (Charakter "Odin" )
2023-04-30, 00:14:17: Request connection to gameserver  "tcp:xxxxxxxx" "TheBurningRoses"
2023-04-30, 00:14:17: Connected to gameserver  "tcp:xxxxxx" "TheBurningRoses"
2023-04-30, 00:14:18: Didn't send news query with params ( 0 2 ) (URL: QUrl("http://xxxxxx/login.php") ) due to too many retries.
2023-04-30, 00:14:22: Error while processing network packet invalid frame group requested

**Comment by Friedrich1980** [comment] 2023-04-29 22:20
as soon as i click on the outfit or the mount the client closes

**Comment by Alexv45** [comment] 2023-04-30 00:14
> as soon as i click on the outfit or the mount the client closes

Did you download the whole game again an try ?
This was fixed on v1.0.3

**Comment by Friedrich1980** [comment] 2023-04-30 00:19
i know it also worked for a while i downloaded the new version today ‎Saturday, ‎30. ‎October ‎2021, ‏‎16:53:30 and since then it hasn't worked again

**Comment by Friedrich1980** [comment] 2023-04-30 00:22
Agregado un TP en Darashia para Ferumbras  , I can get to ferubras but I haven't managed to destroy the stones yet, I've already tested most of the updates

**Comment by Alexv45** [comment] 2023-04-30 08:50
> i know it also worked for a while i downloaded the new version today ‎Saturday, ‎30. ‎October ‎2021, ‏‎16:53:30 and since then it hasn't worked again

![image](https://user-images.githubusercontent.com/89811188/235344283-f5807d43-ecc3-4e61-a4c6-1ead8a4de149.png)

The problem was on xml/outfits.xml , and is now working correctly, check the file the last line on male outfits is:
`<outfit type="1" looktype="1597" name="Ancient Aucar" premium="yes" unlocked="no" enabled="yes" from="store" />`
If not, you need replace for the new file.

**Comment by Alexv45** [comment] 2023-04-30 08:53
> Agregado un TP en Darashia para Ferumbras , I can get to ferubras but I haven't managed to destroy the stones yet, I've already tested most of the updates

We have added a Teleport here,

![image](https://user-images.githubusercontent.com/89811188/235344448-f4195a1c-7525-42fc-83d7-34651854e3a9.png)

**Comment by Friedrich1980** [comment] 2023-04-30 10:04
<outfit type="1" looktype="1597" name="Ancient Aucar" premium="yes" unlocked="no" enabled="yes" from="store" />


work now again thx,




 TP en Darashia para Ferumbras   --> i know i wath ther but i cant kill him on him no dmg and when i kill the elements.... near kristal the dont become dmg

**Closed** 2023-05-02 10:41 UTC
Labels: fixed
